import type { IUserContact } from '../types/IUserContact';

export const mockContacts: IUserContact[] = [
  {
    id: 'ai-assistant',
    email: 'ai@assistant.com',
    name: 'AI Assistant',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=ai',
    status: 'online',
    lastMessage: "I'm here to help you!",
    isAI: true,
  },
  {
    id: 'contact1',
    email: 'alice@example.com',
    name: 'Alice Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    status: 'online',
    lastMessage: 'Hey! How are you doing?',
    unreadCount: 2,
    lastSeen: '2 min ago',
  },
  {
    id: 'contact2',
    email: 'bob@example.com',
    name: 'Bob Smith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    status: 'away',
    lastMessage: "Let's catch up later!",
    lastSeen: '1 hour ago',
  },
  {
    id: 'contact3',
    email: 'carol@example.com',
    name: 'Carol Davis',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carol',
    status: 'busy',
    lastMessage: 'In a meeting, will call back',
    lastSeen: '30 min ago',
  },
  {
    id: 'contact4',
    email: 'david@example.com',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact5',
    email: 'emma@example.com',
    name: 'Emma Thompson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    status: 'online',
    lastMessage: 'Just finished the project!',
    unreadCount: 1,
    lastSeen: '5 min ago',
  },
  {
    id: 'contact6',
    email: 'frank@example.com',
    name: 'Frank Martinez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=frank',
    status: 'away',
    lastMessage: 'Coffee break, back in 15',
    lastSeen: '15 min ago',
  },
  {
    id: 'contact7',
    email: 'grace@example.com',
    name: 'Grace Lee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=grace',
    status: 'online',
    lastMessage: 'Great work on the presentation!',
    unreadCount: 3,
    lastSeen: 'just now',
  },
  {
    id: 'contact8',
    email: 'henry@example.com',
    name: 'Henry Brown',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=henry',
    status: 'busy',
    lastMessage: 'Can we reschedule our call?',
    lastSeen: '2 hours ago',
  },
  {
    id: 'contact9',
    email: 'isabella@example.com',
    name: 'Isabella Garcia',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=isabella',
    status: 'offline',
    lastMessage: 'Have a great weekend!',
    lastSeen: '2 days ago',
  },
  {
    id: 'contact10',
    email: 'jack@example.com',
    name: 'Jack Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jack',
    status: 'online',
    lastMessage: 'The new feature looks amazing!',
    unreadCount: 2,
    lastSeen: '3 min ago',
  },
  {
    id: 'contact11',
    email: 'kate@example.com',
    name: 'Kate Williams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kate',
    status: 'away',
    lastMessage: 'Running late, be there soon',
    lastSeen: '20 min ago',
  },
  {
    id: 'contact12',
    email: 'liam@example.com',
    name: 'Liam Rodriguez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam',
    status: 'busy',
    lastMessage: 'Deep focus mode until 5 PM',
    lastSeen: '1 hour ago',
  },
  {
    id: 'contact13',
    email: 'maya@example.com',
    name: 'Maya Patel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maya',
    status: 'online',
    lastMessage: 'Thanks for the code review!',
    unreadCount: 4,
    lastSeen: 'just now',
  },
  {
    id: 'contact14',
    email: 'noah@example.com',
    name: 'Noah Anderson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=noah',
    status: 'offline',
    lastMessage: 'See you at the team meeting',
    lastSeen: '3 days ago',
  },
];
