import type { IContact } from '../types/IContact';

export const mockContacts: IContact[] = [
  {
    id: 'ai-assistant',
    name: 'AI Assistant',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=ai',
    status: 'online',
    lastMessage: "I'm here to help you!",
    isAI: true,
  },
  {
    id: 'contact1',
    name: 'Alice Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    status: 'online',
    lastMessage: 'Hey! How are you doing?',
    unreadCount: 2,
    lastSeen: '2 min ago',
  },
  {
    id: 'contact2',
    name: 'Bob Smith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    status: 'away',
    lastMessage: "Let's catch up later!",
    lastSeen: '1 hour ago',
  },
  {
    id: 'contact3',
    name: 'Carol Davis',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carol',
    status: 'busy',
    lastMessage: 'In a meeting, will call back',
    lastSeen: '30 min ago',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact4',
    name: 'David Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
  {
    id: 'contact5',
    name: 'David Wilsonss',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    status: 'offline',
    lastMessage: 'Thanks for the help!',
    lastSeen: 'yesterday',
  },
];
